### ISSUE TITLE
如何给搜索匹配动态赋值？

### ISSUE THREAD

**Issue by ZBK1nger** [mindawei/wsSearchView#4]
当搜索框文字发生改变时，调用Api获取相匹配的列表，并动态赋值到搜索匹配的数组上

**Comment by mindawei** [comment]
搜索提示的是在这个地方
https://github.com/mindawei/wsSearchView/blob/master/wxSearchView/wxSearchView.js

// 搜索框输入时候操作
function wxSearchInput(e) {
  var inputValue = e.detail.value;
  // 页面数据
  var temData = __that.data.wxSearchData;
  // 寻找提示值 
  var tipKeys = [];
  if (inputValue && inputValue.length > 0) {
    for (var i = 0; i < __tipKeys.length; i++) {
      var mindKey = __tipKeys[i];
      // 包含字符串
      if (mindKey.indexOf(inputValue) != -1) {
        tipKeys.push(mindKey);
      }
    }
  }
  // 更新数据
  temData.value = inputValue;
  temData.tipKeys = tipKeys;
  // 更新视图
  __that.setData({
    wxSearchData: temData
  });
}

这里应该可以调用api替换 tipKeys 的值。

**Comment by ZBK1nger** [comment]
已实现 感谢开源~
